{{ if .Values.internalFilestore }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-filestore-keys
type: Opaque
stringData:
  accesskey: {{ randAlphaNum 16 }}
  secretkey: {{ randAlphaNum 16 }}
{{ end }}
